# Generated by Django 4.0 on 2022-01-03 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
