# Generated by Django 4.0 on 2022-01-07 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0002_alter_vendor_options_rename_owner_vendor_created_by_and_more'),
        ('cart', '0005_alter_orderitem_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='vendor.vendor'),
        ),
    ]
