# Generated by Django 3.2.9 on 2022-01-14 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_userdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
